
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `Pickup` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/library"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model Pickup
 * 
 */
export type PickupModel = runtime.Types.Result.DefaultSelection<Prisma.$PickupPayload>

export type AggregatePickup = {
  _count: PickupCountAggregateOutputType | null
  _min: PickupMinAggregateOutputType | null
  _max: PickupMaxAggregateOutputType | null
}

export type PickupMinAggregateOutputType = {
  id: string | null
  userId: string | null
  senderName: string | null
  address: string | null
  notes: string | null
  scheduledAt: Date | null
  status: $Enums.PickupStatus | null
  txHash: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type PickupMaxAggregateOutputType = {
  id: string | null
  userId: string | null
  senderName: string | null
  address: string | null
  notes: string | null
  scheduledAt: Date | null
  status: $Enums.PickupStatus | null
  txHash: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type PickupCountAggregateOutputType = {
  id: number
  userId: number
  senderName: number
  address: number
  notes: number
  scheduledAt: number
  status: number
  txHash: number
  createdAt: number
  updatedAt: number
  _all: number
}


export type PickupMinAggregateInputType = {
  id?: true
  userId?: true
  senderName?: true
  address?: true
  notes?: true
  scheduledAt?: true
  status?: true
  txHash?: true
  createdAt?: true
  updatedAt?: true
}

export type PickupMaxAggregateInputType = {
  id?: true
  userId?: true
  senderName?: true
  address?: true
  notes?: true
  scheduledAt?: true
  status?: true
  txHash?: true
  createdAt?: true
  updatedAt?: true
}

export type PickupCountAggregateInputType = {
  id?: true
  userId?: true
  senderName?: true
  address?: true
  notes?: true
  scheduledAt?: true
  status?: true
  txHash?: true
  createdAt?: true
  updatedAt?: true
  _all?: true
}

export type PickupAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Pickup to aggregate.
   */
  where?: Prisma.PickupWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Pickups to fetch.
   */
  orderBy?: Prisma.PickupOrderByWithRelationInput | Prisma.PickupOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.PickupWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Pickups from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Pickups.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned Pickups
  **/
  _count?: true | PickupCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: PickupMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: PickupMaxAggregateInputType
}

export type GetPickupAggregateType<T extends PickupAggregateArgs> = {
      [P in keyof T & keyof AggregatePickup]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregatePickup[P]>
    : Prisma.GetScalarType<T[P], AggregatePickup[P]>
}




export type PickupGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.PickupWhereInput
  orderBy?: Prisma.PickupOrderByWithAggregationInput | Prisma.PickupOrderByWithAggregationInput[]
  by: Prisma.PickupScalarFieldEnum[] | Prisma.PickupScalarFieldEnum
  having?: Prisma.PickupScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: PickupCountAggregateInputType | true
  _min?: PickupMinAggregateInputType
  _max?: PickupMaxAggregateInputType
}

export type PickupGroupByOutputType = {
  id: string
  userId: string
  senderName: string
  address: string
  notes: string | null
  scheduledAt: Date
  status: $Enums.PickupStatus
  txHash: string | null
  createdAt: Date
  updatedAt: Date
  _count: PickupCountAggregateOutputType | null
  _min: PickupMinAggregateOutputType | null
  _max: PickupMaxAggregateOutputType | null
}

type GetPickupGroupByPayload<T extends PickupGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<PickupGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof PickupGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], PickupGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], PickupGroupByOutputType[P]>
      }
    >
  >



export type PickupWhereInput = {
  AND?: Prisma.PickupWhereInput | Prisma.PickupWhereInput[]
  OR?: Prisma.PickupWhereInput[]
  NOT?: Prisma.PickupWhereInput | Prisma.PickupWhereInput[]
  id?: Prisma.StringFilter<"Pickup"> | string
  userId?: Prisma.StringFilter<"Pickup"> | string
  senderName?: Prisma.StringFilter<"Pickup"> | string
  address?: Prisma.StringFilter<"Pickup"> | string
  notes?: Prisma.StringNullableFilter<"Pickup"> | string | null
  scheduledAt?: Prisma.DateTimeFilter<"Pickup"> | Date | string
  status?: Prisma.EnumPickupStatusFilter<"Pickup"> | $Enums.PickupStatus
  txHash?: Prisma.StringNullableFilter<"Pickup"> | string | null
  createdAt?: Prisma.DateTimeFilter<"Pickup"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"Pickup"> | Date | string
  user?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
  token?: Prisma.XOR<Prisma.PickupTokenNullableScalarRelationFilter, Prisma.PickupTokenWhereInput> | null
}

export type PickupOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  senderName?: Prisma.SortOrder
  address?: Prisma.SortOrder
  notes?: Prisma.SortOrderInput | Prisma.SortOrder
  scheduledAt?: Prisma.SortOrder
  status?: Prisma.SortOrder
  txHash?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  user?: Prisma.UserOrderByWithRelationInput
  token?: Prisma.PickupTokenOrderByWithRelationInput
}

export type PickupWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.PickupWhereInput | Prisma.PickupWhereInput[]
  OR?: Prisma.PickupWhereInput[]
  NOT?: Prisma.PickupWhereInput | Prisma.PickupWhereInput[]
  userId?: Prisma.StringFilter<"Pickup"> | string
  senderName?: Prisma.StringFilter<"Pickup"> | string
  address?: Prisma.StringFilter<"Pickup"> | string
  notes?: Prisma.StringNullableFilter<"Pickup"> | string | null
  scheduledAt?: Prisma.DateTimeFilter<"Pickup"> | Date | string
  status?: Prisma.EnumPickupStatusFilter<"Pickup"> | $Enums.PickupStatus
  txHash?: Prisma.StringNullableFilter<"Pickup"> | string | null
  createdAt?: Prisma.DateTimeFilter<"Pickup"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"Pickup"> | Date | string
  user?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
  token?: Prisma.XOR<Prisma.PickupTokenNullableScalarRelationFilter, Prisma.PickupTokenWhereInput> | null
}, "id">

export type PickupOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  senderName?: Prisma.SortOrder
  address?: Prisma.SortOrder
  notes?: Prisma.SortOrderInput | Prisma.SortOrder
  scheduledAt?: Prisma.SortOrder
  status?: Prisma.SortOrder
  txHash?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.PickupCountOrderByAggregateInput
  _max?: Prisma.PickupMaxOrderByAggregateInput
  _min?: Prisma.PickupMinOrderByAggregateInput
}

export type PickupScalarWhereWithAggregatesInput = {
  AND?: Prisma.PickupScalarWhereWithAggregatesInput | Prisma.PickupScalarWhereWithAggregatesInput[]
  OR?: Prisma.PickupScalarWhereWithAggregatesInput[]
  NOT?: Prisma.PickupScalarWhereWithAggregatesInput | Prisma.PickupScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"Pickup"> | string
  userId?: Prisma.StringWithAggregatesFilter<"Pickup"> | string
  senderName?: Prisma.StringWithAggregatesFilter<"Pickup"> | string
  address?: Prisma.StringWithAggregatesFilter<"Pickup"> | string
  notes?: Prisma.StringNullableWithAggregatesFilter<"Pickup"> | string | null
  scheduledAt?: Prisma.DateTimeWithAggregatesFilter<"Pickup"> | Date | string
  status?: Prisma.EnumPickupStatusWithAggregatesFilter<"Pickup"> | $Enums.PickupStatus
  txHash?: Prisma.StringNullableWithAggregatesFilter<"Pickup"> | string | null
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"Pickup"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"Pickup"> | Date | string
}

export type PickupCreateInput = {
  id?: string
  senderName: string
  address: string
  notes?: string | null
  scheduledAt: Date | string
  status?: $Enums.PickupStatus
  txHash?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  user: Prisma.UserCreateNestedOneWithoutPickupsInput
  token?: Prisma.PickupTokenCreateNestedOneWithoutPickupInput
}

export type PickupUncheckedCreateInput = {
  id?: string
  userId: string
  senderName: string
  address: string
  notes?: string | null
  scheduledAt: Date | string
  status?: $Enums.PickupStatus
  txHash?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  token?: Prisma.PickupTokenUncheckedCreateNestedOneWithoutPickupInput
}

export type PickupUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  senderName?: Prisma.StringFieldUpdateOperationsInput | string
  address?: Prisma.StringFieldUpdateOperationsInput | string
  notes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  scheduledAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  status?: Prisma.EnumPickupStatusFieldUpdateOperationsInput | $Enums.PickupStatus
  txHash?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  user?: Prisma.UserUpdateOneRequiredWithoutPickupsNestedInput
  token?: Prisma.PickupTokenUpdateOneWithoutPickupNestedInput
}

export type PickupUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  senderName?: Prisma.StringFieldUpdateOperationsInput | string
  address?: Prisma.StringFieldUpdateOperationsInput | string
  notes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  scheduledAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  status?: Prisma.EnumPickupStatusFieldUpdateOperationsInput | $Enums.PickupStatus
  txHash?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  token?: Prisma.PickupTokenUncheckedUpdateOneWithoutPickupNestedInput
}

export type PickupCreateManyInput = {
  id?: string
  userId: string
  senderName: string
  address: string
  notes?: string | null
  scheduledAt: Date | string
  status?: $Enums.PickupStatus
  txHash?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type PickupUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  senderName?: Prisma.StringFieldUpdateOperationsInput | string
  address?: Prisma.StringFieldUpdateOperationsInput | string
  notes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  scheduledAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  status?: Prisma.EnumPickupStatusFieldUpdateOperationsInput | $Enums.PickupStatus
  txHash?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type PickupUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  senderName?: Prisma.StringFieldUpdateOperationsInput | string
  address?: Prisma.StringFieldUpdateOperationsInput | string
  notes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  scheduledAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  status?: Prisma.EnumPickupStatusFieldUpdateOperationsInput | $Enums.PickupStatus
  txHash?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type PickupListRelationFilter = {
  every?: Prisma.PickupWhereInput
  some?: Prisma.PickupWhereInput
  none?: Prisma.PickupWhereInput
}

export type PickupOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type PickupCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  senderName?: Prisma.SortOrder
  address?: Prisma.SortOrder
  notes?: Prisma.SortOrder
  scheduledAt?: Prisma.SortOrder
  status?: Prisma.SortOrder
  txHash?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type PickupMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  senderName?: Prisma.SortOrder
  address?: Prisma.SortOrder
  notes?: Prisma.SortOrder
  scheduledAt?: Prisma.SortOrder
  status?: Prisma.SortOrder
  txHash?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type PickupMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  senderName?: Prisma.SortOrder
  address?: Prisma.SortOrder
  notes?: Prisma.SortOrder
  scheduledAt?: Prisma.SortOrder
  status?: Prisma.SortOrder
  txHash?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type PickupScalarRelationFilter = {
  is?: Prisma.PickupWhereInput
  isNot?: Prisma.PickupWhereInput
}

export type PickupCreateNestedManyWithoutUserInput = {
  create?: Prisma.XOR<Prisma.PickupCreateWithoutUserInput, Prisma.PickupUncheckedCreateWithoutUserInput> | Prisma.PickupCreateWithoutUserInput[] | Prisma.PickupUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.PickupCreateOrConnectWithoutUserInput | Prisma.PickupCreateOrConnectWithoutUserInput[]
  createMany?: Prisma.PickupCreateManyUserInputEnvelope
  connect?: Prisma.PickupWhereUniqueInput | Prisma.PickupWhereUniqueInput[]
}

export type PickupUncheckedCreateNestedManyWithoutUserInput = {
  create?: Prisma.XOR<Prisma.PickupCreateWithoutUserInput, Prisma.PickupUncheckedCreateWithoutUserInput> | Prisma.PickupCreateWithoutUserInput[] | Prisma.PickupUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.PickupCreateOrConnectWithoutUserInput | Prisma.PickupCreateOrConnectWithoutUserInput[]
  createMany?: Prisma.PickupCreateManyUserInputEnvelope
  connect?: Prisma.PickupWhereUniqueInput | Prisma.PickupWhereUniqueInput[]
}

export type PickupUpdateManyWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.PickupCreateWithoutUserInput, Prisma.PickupUncheckedCreateWithoutUserInput> | Prisma.PickupCreateWithoutUserInput[] | Prisma.PickupUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.PickupCreateOrConnectWithoutUserInput | Prisma.PickupCreateOrConnectWithoutUserInput[]
  upsert?: Prisma.PickupUpsertWithWhereUniqueWithoutUserInput | Prisma.PickupUpsertWithWhereUniqueWithoutUserInput[]
  createMany?: Prisma.PickupCreateManyUserInputEnvelope
  set?: Prisma.PickupWhereUniqueInput | Prisma.PickupWhereUniqueInput[]
  disconnect?: Prisma.PickupWhereUniqueInput | Prisma.PickupWhereUniqueInput[]
  delete?: Prisma.PickupWhereUniqueInput | Prisma.PickupWhereUniqueInput[]
  connect?: Prisma.PickupWhereUniqueInput | Prisma.PickupWhereUniqueInput[]
  update?: Prisma.PickupUpdateWithWhereUniqueWithoutUserInput | Prisma.PickupUpdateWithWhereUniqueWithoutUserInput[]
  updateMany?: Prisma.PickupUpdateManyWithWhereWithoutUserInput | Prisma.PickupUpdateManyWithWhereWithoutUserInput[]
  deleteMany?: Prisma.PickupScalarWhereInput | Prisma.PickupScalarWhereInput[]
}

export type PickupUncheckedUpdateManyWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.PickupCreateWithoutUserInput, Prisma.PickupUncheckedCreateWithoutUserInput> | Prisma.PickupCreateWithoutUserInput[] | Prisma.PickupUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.PickupCreateOrConnectWithoutUserInput | Prisma.PickupCreateOrConnectWithoutUserInput[]
  upsert?: Prisma.PickupUpsertWithWhereUniqueWithoutUserInput | Prisma.PickupUpsertWithWhereUniqueWithoutUserInput[]
  createMany?: Prisma.PickupCreateManyUserInputEnvelope
  set?: Prisma.PickupWhereUniqueInput | Prisma.PickupWhereUniqueInput[]
  disconnect?: Prisma.PickupWhereUniqueInput | Prisma.PickupWhereUniqueInput[]
  delete?: Prisma.PickupWhereUniqueInput | Prisma.PickupWhereUniqueInput[]
  connect?: Prisma.PickupWhereUniqueInput | Prisma.PickupWhereUniqueInput[]
  update?: Prisma.PickupUpdateWithWhereUniqueWithoutUserInput | Prisma.PickupUpdateWithWhereUniqueWithoutUserInput[]
  updateMany?: Prisma.PickupUpdateManyWithWhereWithoutUserInput | Prisma.PickupUpdateManyWithWhereWithoutUserInput[]
  deleteMany?: Prisma.PickupScalarWhereInput | Prisma.PickupScalarWhereInput[]
}

export type EnumPickupStatusFieldUpdateOperationsInput = {
  set?: $Enums.PickupStatus
}

export type PickupCreateNestedOneWithoutTokenInput = {
  create?: Prisma.XOR<Prisma.PickupCreateWithoutTokenInput, Prisma.PickupUncheckedCreateWithoutTokenInput>
  connectOrCreate?: Prisma.PickupCreateOrConnectWithoutTokenInput
  connect?: Prisma.PickupWhereUniqueInput
}

export type PickupUpdateOneRequiredWithoutTokenNestedInput = {
  create?: Prisma.XOR<Prisma.PickupCreateWithoutTokenInput, Prisma.PickupUncheckedCreateWithoutTokenInput>
  connectOrCreate?: Prisma.PickupCreateOrConnectWithoutTokenInput
  upsert?: Prisma.PickupUpsertWithoutTokenInput
  connect?: Prisma.PickupWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.PickupUpdateToOneWithWhereWithoutTokenInput, Prisma.PickupUpdateWithoutTokenInput>, Prisma.PickupUncheckedUpdateWithoutTokenInput>
}

export type PickupCreateWithoutUserInput = {
  id?: string
  senderName: string
  address: string
  notes?: string | null
  scheduledAt: Date | string
  status?: $Enums.PickupStatus
  txHash?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  token?: Prisma.PickupTokenCreateNestedOneWithoutPickupInput
}

export type PickupUncheckedCreateWithoutUserInput = {
  id?: string
  senderName: string
  address: string
  notes?: string | null
  scheduledAt: Date | string
  status?: $Enums.PickupStatus
  txHash?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  token?: Prisma.PickupTokenUncheckedCreateNestedOneWithoutPickupInput
}

export type PickupCreateOrConnectWithoutUserInput = {
  where: Prisma.PickupWhereUniqueInput
  create: Prisma.XOR<Prisma.PickupCreateWithoutUserInput, Prisma.PickupUncheckedCreateWithoutUserInput>
}

export type PickupCreateManyUserInputEnvelope = {
  data: Prisma.PickupCreateManyUserInput | Prisma.PickupCreateManyUserInput[]
  skipDuplicates?: boolean
}

export type PickupUpsertWithWhereUniqueWithoutUserInput = {
  where: Prisma.PickupWhereUniqueInput
  update: Prisma.XOR<Prisma.PickupUpdateWithoutUserInput, Prisma.PickupUncheckedUpdateWithoutUserInput>
  create: Prisma.XOR<Prisma.PickupCreateWithoutUserInput, Prisma.PickupUncheckedCreateWithoutUserInput>
}

export type PickupUpdateWithWhereUniqueWithoutUserInput = {
  where: Prisma.PickupWhereUniqueInput
  data: Prisma.XOR<Prisma.PickupUpdateWithoutUserInput, Prisma.PickupUncheckedUpdateWithoutUserInput>
}

export type PickupUpdateManyWithWhereWithoutUserInput = {
  where: Prisma.PickupScalarWhereInput
  data: Prisma.XOR<Prisma.PickupUpdateManyMutationInput, Prisma.PickupUncheckedUpdateManyWithoutUserInput>
}

export type PickupScalarWhereInput = {
  AND?: Prisma.PickupScalarWhereInput | Prisma.PickupScalarWhereInput[]
  OR?: Prisma.PickupScalarWhereInput[]
  NOT?: Prisma.PickupScalarWhereInput | Prisma.PickupScalarWhereInput[]
  id?: Prisma.StringFilter<"Pickup"> | string
  userId?: Prisma.StringFilter<"Pickup"> | string
  senderName?: Prisma.StringFilter<"Pickup"> | string
  address?: Prisma.StringFilter<"Pickup"> | string
  notes?: Prisma.StringNullableFilter<"Pickup"> | string | null
  scheduledAt?: Prisma.DateTimeFilter<"Pickup"> | Date | string
  status?: Prisma.EnumPickupStatusFilter<"Pickup"> | $Enums.PickupStatus
  txHash?: Prisma.StringNullableFilter<"Pickup"> | string | null
  createdAt?: Prisma.DateTimeFilter<"Pickup"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"Pickup"> | Date | string
}

export type PickupCreateWithoutTokenInput = {
  id?: string
  senderName: string
  address: string
  notes?: string | null
  scheduledAt: Date | string
  status?: $Enums.PickupStatus
  txHash?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  user: Prisma.UserCreateNestedOneWithoutPickupsInput
}

export type PickupUncheckedCreateWithoutTokenInput = {
  id?: string
  userId: string
  senderName: string
  address: string
  notes?: string | null
  scheduledAt: Date | string
  status?: $Enums.PickupStatus
  txHash?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type PickupCreateOrConnectWithoutTokenInput = {
  where: Prisma.PickupWhereUniqueInput
  create: Prisma.XOR<Prisma.PickupCreateWithoutTokenInput, Prisma.PickupUncheckedCreateWithoutTokenInput>
}

export type PickupUpsertWithoutTokenInput = {
  update: Prisma.XOR<Prisma.PickupUpdateWithoutTokenInput, Prisma.PickupUncheckedUpdateWithoutTokenInput>
  create: Prisma.XOR<Prisma.PickupCreateWithoutTokenInput, Prisma.PickupUncheckedCreateWithoutTokenInput>
  where?: Prisma.PickupWhereInput
}

export type PickupUpdateToOneWithWhereWithoutTokenInput = {
  where?: Prisma.PickupWhereInput
  data: Prisma.XOR<Prisma.PickupUpdateWithoutTokenInput, Prisma.PickupUncheckedUpdateWithoutTokenInput>
}

export type PickupUpdateWithoutTokenInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  senderName?: Prisma.StringFieldUpdateOperationsInput | string
  address?: Prisma.StringFieldUpdateOperationsInput | string
  notes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  scheduledAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  status?: Prisma.EnumPickupStatusFieldUpdateOperationsInput | $Enums.PickupStatus
  txHash?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  user?: Prisma.UserUpdateOneRequiredWithoutPickupsNestedInput
}

export type PickupUncheckedUpdateWithoutTokenInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  senderName?: Prisma.StringFieldUpdateOperationsInput | string
  address?: Prisma.StringFieldUpdateOperationsInput | string
  notes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  scheduledAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  status?: Prisma.EnumPickupStatusFieldUpdateOperationsInput | $Enums.PickupStatus
  txHash?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type PickupCreateManyUserInput = {
  id?: string
  senderName: string
  address: string
  notes?: string | null
  scheduledAt: Date | string
  status?: $Enums.PickupStatus
  txHash?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type PickupUpdateWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  senderName?: Prisma.StringFieldUpdateOperationsInput | string
  address?: Prisma.StringFieldUpdateOperationsInput | string
  notes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  scheduledAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  status?: Prisma.EnumPickupStatusFieldUpdateOperationsInput | $Enums.PickupStatus
  txHash?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  token?: Prisma.PickupTokenUpdateOneWithoutPickupNestedInput
}

export type PickupUncheckedUpdateWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  senderName?: Prisma.StringFieldUpdateOperationsInput | string
  address?: Prisma.StringFieldUpdateOperationsInput | string
  notes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  scheduledAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  status?: Prisma.EnumPickupStatusFieldUpdateOperationsInput | $Enums.PickupStatus
  txHash?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  token?: Prisma.PickupTokenUncheckedUpdateOneWithoutPickupNestedInput
}

export type PickupUncheckedUpdateManyWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  senderName?: Prisma.StringFieldUpdateOperationsInput | string
  address?: Prisma.StringFieldUpdateOperationsInput | string
  notes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  scheduledAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  status?: Prisma.EnumPickupStatusFieldUpdateOperationsInput | $Enums.PickupStatus
  txHash?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}



export type PickupSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  userId?: boolean
  senderName?: boolean
  address?: boolean
  notes?: boolean
  scheduledAt?: boolean
  status?: boolean
  txHash?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  token?: boolean | Prisma.Pickup$tokenArgs<ExtArgs>
}, ExtArgs["result"]["pickup"]>

export type PickupSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  userId?: boolean
  senderName?: boolean
  address?: boolean
  notes?: boolean
  scheduledAt?: boolean
  status?: boolean
  txHash?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}, ExtArgs["result"]["pickup"]>

export type PickupSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  userId?: boolean
  senderName?: boolean
  address?: boolean
  notes?: boolean
  scheduledAt?: boolean
  status?: boolean
  txHash?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}, ExtArgs["result"]["pickup"]>

export type PickupSelectScalar = {
  id?: boolean
  userId?: boolean
  senderName?: boolean
  address?: boolean
  notes?: boolean
  scheduledAt?: boolean
  status?: boolean
  txHash?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}

export type PickupOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "userId" | "senderName" | "address" | "notes" | "scheduledAt" | "status" | "txHash" | "createdAt" | "updatedAt", ExtArgs["result"]["pickup"]>
export type PickupInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  token?: boolean | Prisma.Pickup$tokenArgs<ExtArgs>
}
export type PickupIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}
export type PickupIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}

export type $PickupPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "Pickup"
  objects: {
    user: Prisma.$UserPayload<ExtArgs>
    token: Prisma.$PickupTokenPayload<ExtArgs> | null
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    userId: string
    senderName: string
    address: string
    notes: string | null
    scheduledAt: Date
    status: $Enums.PickupStatus
    txHash: string | null
    createdAt: Date
    updatedAt: Date
  }, ExtArgs["result"]["pickup"]>
  composites: {}
}

export type PickupGetPayload<S extends boolean | null | undefined | PickupDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$PickupPayload, S>

export type PickupCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<PickupFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: PickupCountAggregateInputType | true
  }

export interface PickupDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['Pickup'], meta: { name: 'Pickup' } }
  /**
   * Find zero or one Pickup that matches the filter.
   * @param {PickupFindUniqueArgs} args - Arguments to find a Pickup
   * @example
   * // Get one Pickup
   * const pickup = await prisma.pickup.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends PickupFindUniqueArgs>(args: Prisma.SelectSubset<T, PickupFindUniqueArgs<ExtArgs>>): Prisma.Prisma__PickupClient<runtime.Types.Result.GetResult<Prisma.$PickupPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Pickup that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {PickupFindUniqueOrThrowArgs} args - Arguments to find a Pickup
   * @example
   * // Get one Pickup
   * const pickup = await prisma.pickup.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends PickupFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, PickupFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__PickupClient<runtime.Types.Result.GetResult<Prisma.$PickupPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Pickup that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PickupFindFirstArgs} args - Arguments to find a Pickup
   * @example
   * // Get one Pickup
   * const pickup = await prisma.pickup.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends PickupFindFirstArgs>(args?: Prisma.SelectSubset<T, PickupFindFirstArgs<ExtArgs>>): Prisma.Prisma__PickupClient<runtime.Types.Result.GetResult<Prisma.$PickupPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Pickup that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PickupFindFirstOrThrowArgs} args - Arguments to find a Pickup
   * @example
   * // Get one Pickup
   * const pickup = await prisma.pickup.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends PickupFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, PickupFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__PickupClient<runtime.Types.Result.GetResult<Prisma.$PickupPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Pickups that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PickupFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Pickups
   * const pickups = await prisma.pickup.findMany()
   * 
   * // Get first 10 Pickups
   * const pickups = await prisma.pickup.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const pickupWithIdOnly = await prisma.pickup.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends PickupFindManyArgs>(args?: Prisma.SelectSubset<T, PickupFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$PickupPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Pickup.
   * @param {PickupCreateArgs} args - Arguments to create a Pickup.
   * @example
   * // Create one Pickup
   * const Pickup = await prisma.pickup.create({
   *   data: {
   *     // ... data to create a Pickup
   *   }
   * })
   * 
   */
  create<T extends PickupCreateArgs>(args: Prisma.SelectSubset<T, PickupCreateArgs<ExtArgs>>): Prisma.Prisma__PickupClient<runtime.Types.Result.GetResult<Prisma.$PickupPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Pickups.
   * @param {PickupCreateManyArgs} args - Arguments to create many Pickups.
   * @example
   * // Create many Pickups
   * const pickup = await prisma.pickup.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends PickupCreateManyArgs>(args?: Prisma.SelectSubset<T, PickupCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Pickups and returns the data saved in the database.
   * @param {PickupCreateManyAndReturnArgs} args - Arguments to create many Pickups.
   * @example
   * // Create many Pickups
   * const pickup = await prisma.pickup.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Pickups and only return the `id`
   * const pickupWithIdOnly = await prisma.pickup.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends PickupCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, PickupCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$PickupPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Pickup.
   * @param {PickupDeleteArgs} args - Arguments to delete one Pickup.
   * @example
   * // Delete one Pickup
   * const Pickup = await prisma.pickup.delete({
   *   where: {
   *     // ... filter to delete one Pickup
   *   }
   * })
   * 
   */
  delete<T extends PickupDeleteArgs>(args: Prisma.SelectSubset<T, PickupDeleteArgs<ExtArgs>>): Prisma.Prisma__PickupClient<runtime.Types.Result.GetResult<Prisma.$PickupPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Pickup.
   * @param {PickupUpdateArgs} args - Arguments to update one Pickup.
   * @example
   * // Update one Pickup
   * const pickup = await prisma.pickup.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends PickupUpdateArgs>(args: Prisma.SelectSubset<T, PickupUpdateArgs<ExtArgs>>): Prisma.Prisma__PickupClient<runtime.Types.Result.GetResult<Prisma.$PickupPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Pickups.
   * @param {PickupDeleteManyArgs} args - Arguments to filter Pickups to delete.
   * @example
   * // Delete a few Pickups
   * const { count } = await prisma.pickup.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends PickupDeleteManyArgs>(args?: Prisma.SelectSubset<T, PickupDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Pickups.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PickupUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Pickups
   * const pickup = await prisma.pickup.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends PickupUpdateManyArgs>(args: Prisma.SelectSubset<T, PickupUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Pickups and returns the data updated in the database.
   * @param {PickupUpdateManyAndReturnArgs} args - Arguments to update many Pickups.
   * @example
   * // Update many Pickups
   * const pickup = await prisma.pickup.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Pickups and only return the `id`
   * const pickupWithIdOnly = await prisma.pickup.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends PickupUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, PickupUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$PickupPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Pickup.
   * @param {PickupUpsertArgs} args - Arguments to update or create a Pickup.
   * @example
   * // Update or create a Pickup
   * const pickup = await prisma.pickup.upsert({
   *   create: {
   *     // ... data to create a Pickup
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Pickup we want to update
   *   }
   * })
   */
  upsert<T extends PickupUpsertArgs>(args: Prisma.SelectSubset<T, PickupUpsertArgs<ExtArgs>>): Prisma.Prisma__PickupClient<runtime.Types.Result.GetResult<Prisma.$PickupPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Pickups.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PickupCountArgs} args - Arguments to filter Pickups to count.
   * @example
   * // Count the number of Pickups
   * const count = await prisma.pickup.count({
   *   where: {
   *     // ... the filter for the Pickups we want to count
   *   }
   * })
  **/
  count<T extends PickupCountArgs>(
    args?: Prisma.Subset<T, PickupCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], PickupCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Pickup.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PickupAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends PickupAggregateArgs>(args: Prisma.Subset<T, PickupAggregateArgs>): Prisma.PrismaPromise<GetPickupAggregateType<T>>

  /**
   * Group by Pickup.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PickupGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends PickupGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: PickupGroupByArgs['orderBy'] }
      : { orderBy?: PickupGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, PickupGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetPickupGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the Pickup model
 */
readonly fields: PickupFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for Pickup.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__PickupClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  user<T extends Prisma.UserDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.UserDefaultArgs<ExtArgs>>): Prisma.Prisma__UserClient<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  token<T extends Prisma.Pickup$tokenArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Pickup$tokenArgs<ExtArgs>>): Prisma.Prisma__PickupTokenClient<runtime.Types.Result.GetResult<Prisma.$PickupTokenPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the Pickup model
 */
export interface PickupFieldRefs {
  readonly id: Prisma.FieldRef<"Pickup", 'String'>
  readonly userId: Prisma.FieldRef<"Pickup", 'String'>
  readonly senderName: Prisma.FieldRef<"Pickup", 'String'>
  readonly address: Prisma.FieldRef<"Pickup", 'String'>
  readonly notes: Prisma.FieldRef<"Pickup", 'String'>
  readonly scheduledAt: Prisma.FieldRef<"Pickup", 'DateTime'>
  readonly status: Prisma.FieldRef<"Pickup", 'PickupStatus'>
  readonly txHash: Prisma.FieldRef<"Pickup", 'String'>
  readonly createdAt: Prisma.FieldRef<"Pickup", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"Pickup", 'DateTime'>
}
    

// Custom InputTypes
/**
 * Pickup findUnique
 */
export type PickupFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Pickup
   */
  select?: Prisma.PickupSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Pickup
   */
  omit?: Prisma.PickupOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PickupInclude<ExtArgs> | null
  /**
   * Filter, which Pickup to fetch.
   */
  where: Prisma.PickupWhereUniqueInput
}

/**
 * Pickup findUniqueOrThrow
 */
export type PickupFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Pickup
   */
  select?: Prisma.PickupSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Pickup
   */
  omit?: Prisma.PickupOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PickupInclude<ExtArgs> | null
  /**
   * Filter, which Pickup to fetch.
   */
  where: Prisma.PickupWhereUniqueInput
}

/**
 * Pickup findFirst
 */
export type PickupFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Pickup
   */
  select?: Prisma.PickupSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Pickup
   */
  omit?: Prisma.PickupOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PickupInclude<ExtArgs> | null
  /**
   * Filter, which Pickup to fetch.
   */
  where?: Prisma.PickupWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Pickups to fetch.
   */
  orderBy?: Prisma.PickupOrderByWithRelationInput | Prisma.PickupOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Pickups.
   */
  cursor?: Prisma.PickupWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Pickups from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Pickups.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Pickups.
   */
  distinct?: Prisma.PickupScalarFieldEnum | Prisma.PickupScalarFieldEnum[]
}

/**
 * Pickup findFirstOrThrow
 */
export type PickupFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Pickup
   */
  select?: Prisma.PickupSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Pickup
   */
  omit?: Prisma.PickupOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PickupInclude<ExtArgs> | null
  /**
   * Filter, which Pickup to fetch.
   */
  where?: Prisma.PickupWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Pickups to fetch.
   */
  orderBy?: Prisma.PickupOrderByWithRelationInput | Prisma.PickupOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Pickups.
   */
  cursor?: Prisma.PickupWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Pickups from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Pickups.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Pickups.
   */
  distinct?: Prisma.PickupScalarFieldEnum | Prisma.PickupScalarFieldEnum[]
}

/**
 * Pickup findMany
 */
export type PickupFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Pickup
   */
  select?: Prisma.PickupSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Pickup
   */
  omit?: Prisma.PickupOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PickupInclude<ExtArgs> | null
  /**
   * Filter, which Pickups to fetch.
   */
  where?: Prisma.PickupWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Pickups to fetch.
   */
  orderBy?: Prisma.PickupOrderByWithRelationInput | Prisma.PickupOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing Pickups.
   */
  cursor?: Prisma.PickupWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Pickups from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Pickups.
   */
  skip?: number
  distinct?: Prisma.PickupScalarFieldEnum | Prisma.PickupScalarFieldEnum[]
}

/**
 * Pickup create
 */
export type PickupCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Pickup
   */
  select?: Prisma.PickupSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Pickup
   */
  omit?: Prisma.PickupOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PickupInclude<ExtArgs> | null
  /**
   * The data needed to create a Pickup.
   */
  data: Prisma.XOR<Prisma.PickupCreateInput, Prisma.PickupUncheckedCreateInput>
}

/**
 * Pickup createMany
 */
export type PickupCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many Pickups.
   */
  data: Prisma.PickupCreateManyInput | Prisma.PickupCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * Pickup createManyAndReturn
 */
export type PickupCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Pickup
   */
  select?: Prisma.PickupSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Pickup
   */
  omit?: Prisma.PickupOmit<ExtArgs> | null
  /**
   * The data used to create many Pickups.
   */
  data: Prisma.PickupCreateManyInput | Prisma.PickupCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PickupIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * Pickup update
 */
export type PickupUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Pickup
   */
  select?: Prisma.PickupSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Pickup
   */
  omit?: Prisma.PickupOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PickupInclude<ExtArgs> | null
  /**
   * The data needed to update a Pickup.
   */
  data: Prisma.XOR<Prisma.PickupUpdateInput, Prisma.PickupUncheckedUpdateInput>
  /**
   * Choose, which Pickup to update.
   */
  where: Prisma.PickupWhereUniqueInput
}

/**
 * Pickup updateMany
 */
export type PickupUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update Pickups.
   */
  data: Prisma.XOR<Prisma.PickupUpdateManyMutationInput, Prisma.PickupUncheckedUpdateManyInput>
  /**
   * Filter which Pickups to update
   */
  where?: Prisma.PickupWhereInput
  /**
   * Limit how many Pickups to update.
   */
  limit?: number
}

/**
 * Pickup updateManyAndReturn
 */
export type PickupUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Pickup
   */
  select?: Prisma.PickupSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Pickup
   */
  omit?: Prisma.PickupOmit<ExtArgs> | null
  /**
   * The data used to update Pickups.
   */
  data: Prisma.XOR<Prisma.PickupUpdateManyMutationInput, Prisma.PickupUncheckedUpdateManyInput>
  /**
   * Filter which Pickups to update
   */
  where?: Prisma.PickupWhereInput
  /**
   * Limit how many Pickups to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PickupIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * Pickup upsert
 */
export type PickupUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Pickup
   */
  select?: Prisma.PickupSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Pickup
   */
  omit?: Prisma.PickupOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PickupInclude<ExtArgs> | null
  /**
   * The filter to search for the Pickup to update in case it exists.
   */
  where: Prisma.PickupWhereUniqueInput
  /**
   * In case the Pickup found by the `where` argument doesn't exist, create a new Pickup with this data.
   */
  create: Prisma.XOR<Prisma.PickupCreateInput, Prisma.PickupUncheckedCreateInput>
  /**
   * In case the Pickup was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.PickupUpdateInput, Prisma.PickupUncheckedUpdateInput>
}

/**
 * Pickup delete
 */
export type PickupDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Pickup
   */
  select?: Prisma.PickupSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Pickup
   */
  omit?: Prisma.PickupOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PickupInclude<ExtArgs> | null
  /**
   * Filter which Pickup to delete.
   */
  where: Prisma.PickupWhereUniqueInput
}

/**
 * Pickup deleteMany
 */
export type PickupDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Pickups to delete
   */
  where?: Prisma.PickupWhereInput
  /**
   * Limit how many Pickups to delete.
   */
  limit?: number
}

/**
 * Pickup.token
 */
export type Pickup$tokenArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PickupToken
   */
  select?: Prisma.PickupTokenSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PickupToken
   */
  omit?: Prisma.PickupTokenOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PickupTokenInclude<ExtArgs> | null
  where?: Prisma.PickupTokenWhereInput
}

/**
 * Pickup without action
 */
export type PickupDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Pickup
   */
  select?: Prisma.PickupSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Pickup
   */
  omit?: Prisma.PickupOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PickupInclude<ExtArgs> | null
}
