
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `PickupToken` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/library"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model PickupToken
 * 
 */
export type PickupTokenModel = runtime.Types.Result.DefaultSelection<Prisma.$PickupTokenPayload>

export type AggregatePickupToken = {
  _count: PickupTokenCountAggregateOutputType | null
  _avg: PickupTokenAvgAggregateOutputType | null
  _sum: PickupTokenSumAggregateOutputType | null
  _min: PickupTokenMinAggregateOutputType | null
  _max: PickupTokenMaxAggregateOutputType | null
}

export type PickupTokenAvgAggregateOutputType = {
  amount: number | null
}

export type PickupTokenSumAggregateOutputType = {
  amount: number | null
}

export type PickupTokenMinAggregateOutputType = {
  id: string | null
  pickupId: string | null
  toWallet: string | null
  amount: number | null
  txHash: string | null
  mintedAt: Date | null
}

export type PickupTokenMaxAggregateOutputType = {
  id: string | null
  pickupId: string | null
  toWallet: string | null
  amount: number | null
  txHash: string | null
  mintedAt: Date | null
}

export type PickupTokenCountAggregateOutputType = {
  id: number
  pickupId: number
  toWallet: number
  amount: number
  txHash: number
  mintedAt: number
  _all: number
}


export type PickupTokenAvgAggregateInputType = {
  amount?: true
}

export type PickupTokenSumAggregateInputType = {
  amount?: true
}

export type PickupTokenMinAggregateInputType = {
  id?: true
  pickupId?: true
  toWallet?: true
  amount?: true
  txHash?: true
  mintedAt?: true
}

export type PickupTokenMaxAggregateInputType = {
  id?: true
  pickupId?: true
  toWallet?: true
  amount?: true
  txHash?: true
  mintedAt?: true
}

export type PickupTokenCountAggregateInputType = {
  id?: true
  pickupId?: true
  toWallet?: true
  amount?: true
  txHash?: true
  mintedAt?: true
  _all?: true
}

export type PickupTokenAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which PickupToken to aggregate.
   */
  where?: Prisma.PickupTokenWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of PickupTokens to fetch.
   */
  orderBy?: Prisma.PickupTokenOrderByWithRelationInput | Prisma.PickupTokenOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.PickupTokenWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` PickupTokens from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` PickupTokens.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned PickupTokens
  **/
  _count?: true | PickupTokenCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: PickupTokenAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: PickupTokenSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: PickupTokenMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: PickupTokenMaxAggregateInputType
}

export type GetPickupTokenAggregateType<T extends PickupTokenAggregateArgs> = {
      [P in keyof T & keyof AggregatePickupToken]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregatePickupToken[P]>
    : Prisma.GetScalarType<T[P], AggregatePickupToken[P]>
}




export type PickupTokenGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.PickupTokenWhereInput
  orderBy?: Prisma.PickupTokenOrderByWithAggregationInput | Prisma.PickupTokenOrderByWithAggregationInput[]
  by: Prisma.PickupTokenScalarFieldEnum[] | Prisma.PickupTokenScalarFieldEnum
  having?: Prisma.PickupTokenScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: PickupTokenCountAggregateInputType | true
  _avg?: PickupTokenAvgAggregateInputType
  _sum?: PickupTokenSumAggregateInputType
  _min?: PickupTokenMinAggregateInputType
  _max?: PickupTokenMaxAggregateInputType
}

export type PickupTokenGroupByOutputType = {
  id: string
  pickupId: string
  toWallet: string
  amount: number
  txHash: string | null
  mintedAt: Date
  _count: PickupTokenCountAggregateOutputType | null
  _avg: PickupTokenAvgAggregateOutputType | null
  _sum: PickupTokenSumAggregateOutputType | null
  _min: PickupTokenMinAggregateOutputType | null
  _max: PickupTokenMaxAggregateOutputType | null
}

type GetPickupTokenGroupByPayload<T extends PickupTokenGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<PickupTokenGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof PickupTokenGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], PickupTokenGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], PickupTokenGroupByOutputType[P]>
      }
    >
  >



export type PickupTokenWhereInput = {
  AND?: Prisma.PickupTokenWhereInput | Prisma.PickupTokenWhereInput[]
  OR?: Prisma.PickupTokenWhereInput[]
  NOT?: Prisma.PickupTokenWhereInput | Prisma.PickupTokenWhereInput[]
  id?: Prisma.StringFilter<"PickupToken"> | string
  pickupId?: Prisma.StringFilter<"PickupToken"> | string
  toWallet?: Prisma.StringFilter<"PickupToken"> | string
  amount?: Prisma.IntFilter<"PickupToken"> | number
  txHash?: Prisma.StringNullableFilter<"PickupToken"> | string | null
  mintedAt?: Prisma.DateTimeFilter<"PickupToken"> | Date | string
  pickup?: Prisma.XOR<Prisma.PickupScalarRelationFilter, Prisma.PickupWhereInput>
}

export type PickupTokenOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  pickupId?: Prisma.SortOrder
  toWallet?: Prisma.SortOrder
  amount?: Prisma.SortOrder
  txHash?: Prisma.SortOrderInput | Prisma.SortOrder
  mintedAt?: Prisma.SortOrder
  pickup?: Prisma.PickupOrderByWithRelationInput
}

export type PickupTokenWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  pickupId?: string
  AND?: Prisma.PickupTokenWhereInput | Prisma.PickupTokenWhereInput[]
  OR?: Prisma.PickupTokenWhereInput[]
  NOT?: Prisma.PickupTokenWhereInput | Prisma.PickupTokenWhereInput[]
  toWallet?: Prisma.StringFilter<"PickupToken"> | string
  amount?: Prisma.IntFilter<"PickupToken"> | number
  txHash?: Prisma.StringNullableFilter<"PickupToken"> | string | null
  mintedAt?: Prisma.DateTimeFilter<"PickupToken"> | Date | string
  pickup?: Prisma.XOR<Prisma.PickupScalarRelationFilter, Prisma.PickupWhereInput>
}, "id" | "pickupId">

export type PickupTokenOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  pickupId?: Prisma.SortOrder
  toWallet?: Prisma.SortOrder
  amount?: Prisma.SortOrder
  txHash?: Prisma.SortOrderInput | Prisma.SortOrder
  mintedAt?: Prisma.SortOrder
  _count?: Prisma.PickupTokenCountOrderByAggregateInput
  _avg?: Prisma.PickupTokenAvgOrderByAggregateInput
  _max?: Prisma.PickupTokenMaxOrderByAggregateInput
  _min?: Prisma.PickupTokenMinOrderByAggregateInput
  _sum?: Prisma.PickupTokenSumOrderByAggregateInput
}

export type PickupTokenScalarWhereWithAggregatesInput = {
  AND?: Prisma.PickupTokenScalarWhereWithAggregatesInput | Prisma.PickupTokenScalarWhereWithAggregatesInput[]
  OR?: Prisma.PickupTokenScalarWhereWithAggregatesInput[]
  NOT?: Prisma.PickupTokenScalarWhereWithAggregatesInput | Prisma.PickupTokenScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"PickupToken"> | string
  pickupId?: Prisma.StringWithAggregatesFilter<"PickupToken"> | string
  toWallet?: Prisma.StringWithAggregatesFilter<"PickupToken"> | string
  amount?: Prisma.IntWithAggregatesFilter<"PickupToken"> | number
  txHash?: Prisma.StringNullableWithAggregatesFilter<"PickupToken"> | string | null
  mintedAt?: Prisma.DateTimeWithAggregatesFilter<"PickupToken"> | Date | string
}

export type PickupTokenCreateInput = {
  id?: string
  toWallet: string
  amount?: number
  txHash?: string | null
  mintedAt?: Date | string
  pickup: Prisma.PickupCreateNestedOneWithoutTokenInput
}

export type PickupTokenUncheckedCreateInput = {
  id?: string
  pickupId: string
  toWallet: string
  amount?: number
  txHash?: string | null
  mintedAt?: Date | string
}

export type PickupTokenUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  toWallet?: Prisma.StringFieldUpdateOperationsInput | string
  amount?: Prisma.IntFieldUpdateOperationsInput | number
  txHash?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  mintedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  pickup?: Prisma.PickupUpdateOneRequiredWithoutTokenNestedInput
}

export type PickupTokenUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  pickupId?: Prisma.StringFieldUpdateOperationsInput | string
  toWallet?: Prisma.StringFieldUpdateOperationsInput | string
  amount?: Prisma.IntFieldUpdateOperationsInput | number
  txHash?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  mintedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type PickupTokenCreateManyInput = {
  id?: string
  pickupId: string
  toWallet: string
  amount?: number
  txHash?: string | null
  mintedAt?: Date | string
}

export type PickupTokenUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  toWallet?: Prisma.StringFieldUpdateOperationsInput | string
  amount?: Prisma.IntFieldUpdateOperationsInput | number
  txHash?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  mintedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type PickupTokenUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  pickupId?: Prisma.StringFieldUpdateOperationsInput | string
  toWallet?: Prisma.StringFieldUpdateOperationsInput | string
  amount?: Prisma.IntFieldUpdateOperationsInput | number
  txHash?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  mintedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type PickupTokenNullableScalarRelationFilter = {
  is?: Prisma.PickupTokenWhereInput | null
  isNot?: Prisma.PickupTokenWhereInput | null
}

export type PickupTokenCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  pickupId?: Prisma.SortOrder
  toWallet?: Prisma.SortOrder
  amount?: Prisma.SortOrder
  txHash?: Prisma.SortOrder
  mintedAt?: Prisma.SortOrder
}

export type PickupTokenAvgOrderByAggregateInput = {
  amount?: Prisma.SortOrder
}

export type PickupTokenMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  pickupId?: Prisma.SortOrder
  toWallet?: Prisma.SortOrder
  amount?: Prisma.SortOrder
  txHash?: Prisma.SortOrder
  mintedAt?: Prisma.SortOrder
}

export type PickupTokenMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  pickupId?: Prisma.SortOrder
  toWallet?: Prisma.SortOrder
  amount?: Prisma.SortOrder
  txHash?: Prisma.SortOrder
  mintedAt?: Prisma.SortOrder
}

export type PickupTokenSumOrderByAggregateInput = {
  amount?: Prisma.SortOrder
}

export type PickupTokenCreateNestedOneWithoutPickupInput = {
  create?: Prisma.XOR<Prisma.PickupTokenCreateWithoutPickupInput, Prisma.PickupTokenUncheckedCreateWithoutPickupInput>
  connectOrCreate?: Prisma.PickupTokenCreateOrConnectWithoutPickupInput
  connect?: Prisma.PickupTokenWhereUniqueInput
}

export type PickupTokenUncheckedCreateNestedOneWithoutPickupInput = {
  create?: Prisma.XOR<Prisma.PickupTokenCreateWithoutPickupInput, Prisma.PickupTokenUncheckedCreateWithoutPickupInput>
  connectOrCreate?: Prisma.PickupTokenCreateOrConnectWithoutPickupInput
  connect?: Prisma.PickupTokenWhereUniqueInput
}

export type PickupTokenUpdateOneWithoutPickupNestedInput = {
  create?: Prisma.XOR<Prisma.PickupTokenCreateWithoutPickupInput, Prisma.PickupTokenUncheckedCreateWithoutPickupInput>
  connectOrCreate?: Prisma.PickupTokenCreateOrConnectWithoutPickupInput
  upsert?: Prisma.PickupTokenUpsertWithoutPickupInput
  disconnect?: Prisma.PickupTokenWhereInput | boolean
  delete?: Prisma.PickupTokenWhereInput | boolean
  connect?: Prisma.PickupTokenWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.PickupTokenUpdateToOneWithWhereWithoutPickupInput, Prisma.PickupTokenUpdateWithoutPickupInput>, Prisma.PickupTokenUncheckedUpdateWithoutPickupInput>
}

export type PickupTokenUncheckedUpdateOneWithoutPickupNestedInput = {
  create?: Prisma.XOR<Prisma.PickupTokenCreateWithoutPickupInput, Prisma.PickupTokenUncheckedCreateWithoutPickupInput>
  connectOrCreate?: Prisma.PickupTokenCreateOrConnectWithoutPickupInput
  upsert?: Prisma.PickupTokenUpsertWithoutPickupInput
  disconnect?: Prisma.PickupTokenWhereInput | boolean
  delete?: Prisma.PickupTokenWhereInput | boolean
  connect?: Prisma.PickupTokenWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.PickupTokenUpdateToOneWithWhereWithoutPickupInput, Prisma.PickupTokenUpdateWithoutPickupInput>, Prisma.PickupTokenUncheckedUpdateWithoutPickupInput>
}

export type PickupTokenCreateWithoutPickupInput = {
  id?: string
  toWallet: string
  amount?: number
  txHash?: string | null
  mintedAt?: Date | string
}

export type PickupTokenUncheckedCreateWithoutPickupInput = {
  id?: string
  toWallet: string
  amount?: number
  txHash?: string | null
  mintedAt?: Date | string
}

export type PickupTokenCreateOrConnectWithoutPickupInput = {
  where: Prisma.PickupTokenWhereUniqueInput
  create: Prisma.XOR<Prisma.PickupTokenCreateWithoutPickupInput, Prisma.PickupTokenUncheckedCreateWithoutPickupInput>
}

export type PickupTokenUpsertWithoutPickupInput = {
  update: Prisma.XOR<Prisma.PickupTokenUpdateWithoutPickupInput, Prisma.PickupTokenUncheckedUpdateWithoutPickupInput>
  create: Prisma.XOR<Prisma.PickupTokenCreateWithoutPickupInput, Prisma.PickupTokenUncheckedCreateWithoutPickupInput>
  where?: Prisma.PickupTokenWhereInput
}

export type PickupTokenUpdateToOneWithWhereWithoutPickupInput = {
  where?: Prisma.PickupTokenWhereInput
  data: Prisma.XOR<Prisma.PickupTokenUpdateWithoutPickupInput, Prisma.PickupTokenUncheckedUpdateWithoutPickupInput>
}

export type PickupTokenUpdateWithoutPickupInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  toWallet?: Prisma.StringFieldUpdateOperationsInput | string
  amount?: Prisma.IntFieldUpdateOperationsInput | number
  txHash?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  mintedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type PickupTokenUncheckedUpdateWithoutPickupInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  toWallet?: Prisma.StringFieldUpdateOperationsInput | string
  amount?: Prisma.IntFieldUpdateOperationsInput | number
  txHash?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  mintedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}



export type PickupTokenSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  pickupId?: boolean
  toWallet?: boolean
  amount?: boolean
  txHash?: boolean
  mintedAt?: boolean
  pickup?: boolean | Prisma.PickupDefaultArgs<ExtArgs>
}, ExtArgs["result"]["pickupToken"]>

export type PickupTokenSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  pickupId?: boolean
  toWallet?: boolean
  amount?: boolean
  txHash?: boolean
  mintedAt?: boolean
  pickup?: boolean | Prisma.PickupDefaultArgs<ExtArgs>
}, ExtArgs["result"]["pickupToken"]>

export type PickupTokenSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  pickupId?: boolean
  toWallet?: boolean
  amount?: boolean
  txHash?: boolean
  mintedAt?: boolean
  pickup?: boolean | Prisma.PickupDefaultArgs<ExtArgs>
}, ExtArgs["result"]["pickupToken"]>

export type PickupTokenSelectScalar = {
  id?: boolean
  pickupId?: boolean
  toWallet?: boolean
  amount?: boolean
  txHash?: boolean
  mintedAt?: boolean
}

export type PickupTokenOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "pickupId" | "toWallet" | "amount" | "txHash" | "mintedAt", ExtArgs["result"]["pickupToken"]>
export type PickupTokenInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  pickup?: boolean | Prisma.PickupDefaultArgs<ExtArgs>
}
export type PickupTokenIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  pickup?: boolean | Prisma.PickupDefaultArgs<ExtArgs>
}
export type PickupTokenIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  pickup?: boolean | Prisma.PickupDefaultArgs<ExtArgs>
}

export type $PickupTokenPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "PickupToken"
  objects: {
    pickup: Prisma.$PickupPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    pickupId: string
    toWallet: string
    amount: number
    txHash: string | null
    mintedAt: Date
  }, ExtArgs["result"]["pickupToken"]>
  composites: {}
}

export type PickupTokenGetPayload<S extends boolean | null | undefined | PickupTokenDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$PickupTokenPayload, S>

export type PickupTokenCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<PickupTokenFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: PickupTokenCountAggregateInputType | true
  }

export interface PickupTokenDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['PickupToken'], meta: { name: 'PickupToken' } }
  /**
   * Find zero or one PickupToken that matches the filter.
   * @param {PickupTokenFindUniqueArgs} args - Arguments to find a PickupToken
   * @example
   * // Get one PickupToken
   * const pickupToken = await prisma.pickupToken.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends PickupTokenFindUniqueArgs>(args: Prisma.SelectSubset<T, PickupTokenFindUniqueArgs<ExtArgs>>): Prisma.Prisma__PickupTokenClient<runtime.Types.Result.GetResult<Prisma.$PickupTokenPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one PickupToken that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {PickupTokenFindUniqueOrThrowArgs} args - Arguments to find a PickupToken
   * @example
   * // Get one PickupToken
   * const pickupToken = await prisma.pickupToken.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends PickupTokenFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, PickupTokenFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__PickupTokenClient<runtime.Types.Result.GetResult<Prisma.$PickupTokenPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first PickupToken that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PickupTokenFindFirstArgs} args - Arguments to find a PickupToken
   * @example
   * // Get one PickupToken
   * const pickupToken = await prisma.pickupToken.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends PickupTokenFindFirstArgs>(args?: Prisma.SelectSubset<T, PickupTokenFindFirstArgs<ExtArgs>>): Prisma.Prisma__PickupTokenClient<runtime.Types.Result.GetResult<Prisma.$PickupTokenPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first PickupToken that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PickupTokenFindFirstOrThrowArgs} args - Arguments to find a PickupToken
   * @example
   * // Get one PickupToken
   * const pickupToken = await prisma.pickupToken.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends PickupTokenFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, PickupTokenFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__PickupTokenClient<runtime.Types.Result.GetResult<Prisma.$PickupTokenPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more PickupTokens that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PickupTokenFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all PickupTokens
   * const pickupTokens = await prisma.pickupToken.findMany()
   * 
   * // Get first 10 PickupTokens
   * const pickupTokens = await prisma.pickupToken.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const pickupTokenWithIdOnly = await prisma.pickupToken.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends PickupTokenFindManyArgs>(args?: Prisma.SelectSubset<T, PickupTokenFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$PickupTokenPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a PickupToken.
   * @param {PickupTokenCreateArgs} args - Arguments to create a PickupToken.
   * @example
   * // Create one PickupToken
   * const PickupToken = await prisma.pickupToken.create({
   *   data: {
   *     // ... data to create a PickupToken
   *   }
   * })
   * 
   */
  create<T extends PickupTokenCreateArgs>(args: Prisma.SelectSubset<T, PickupTokenCreateArgs<ExtArgs>>): Prisma.Prisma__PickupTokenClient<runtime.Types.Result.GetResult<Prisma.$PickupTokenPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many PickupTokens.
   * @param {PickupTokenCreateManyArgs} args - Arguments to create many PickupTokens.
   * @example
   * // Create many PickupTokens
   * const pickupToken = await prisma.pickupToken.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends PickupTokenCreateManyArgs>(args?: Prisma.SelectSubset<T, PickupTokenCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many PickupTokens and returns the data saved in the database.
   * @param {PickupTokenCreateManyAndReturnArgs} args - Arguments to create many PickupTokens.
   * @example
   * // Create many PickupTokens
   * const pickupToken = await prisma.pickupToken.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many PickupTokens and only return the `id`
   * const pickupTokenWithIdOnly = await prisma.pickupToken.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends PickupTokenCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, PickupTokenCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$PickupTokenPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a PickupToken.
   * @param {PickupTokenDeleteArgs} args - Arguments to delete one PickupToken.
   * @example
   * // Delete one PickupToken
   * const PickupToken = await prisma.pickupToken.delete({
   *   where: {
   *     // ... filter to delete one PickupToken
   *   }
   * })
   * 
   */
  delete<T extends PickupTokenDeleteArgs>(args: Prisma.SelectSubset<T, PickupTokenDeleteArgs<ExtArgs>>): Prisma.Prisma__PickupTokenClient<runtime.Types.Result.GetResult<Prisma.$PickupTokenPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one PickupToken.
   * @param {PickupTokenUpdateArgs} args - Arguments to update one PickupToken.
   * @example
   * // Update one PickupToken
   * const pickupToken = await prisma.pickupToken.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends PickupTokenUpdateArgs>(args: Prisma.SelectSubset<T, PickupTokenUpdateArgs<ExtArgs>>): Prisma.Prisma__PickupTokenClient<runtime.Types.Result.GetResult<Prisma.$PickupTokenPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more PickupTokens.
   * @param {PickupTokenDeleteManyArgs} args - Arguments to filter PickupTokens to delete.
   * @example
   * // Delete a few PickupTokens
   * const { count } = await prisma.pickupToken.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends PickupTokenDeleteManyArgs>(args?: Prisma.SelectSubset<T, PickupTokenDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more PickupTokens.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PickupTokenUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many PickupTokens
   * const pickupToken = await prisma.pickupToken.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends PickupTokenUpdateManyArgs>(args: Prisma.SelectSubset<T, PickupTokenUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more PickupTokens and returns the data updated in the database.
   * @param {PickupTokenUpdateManyAndReturnArgs} args - Arguments to update many PickupTokens.
   * @example
   * // Update many PickupTokens
   * const pickupToken = await prisma.pickupToken.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more PickupTokens and only return the `id`
   * const pickupTokenWithIdOnly = await prisma.pickupToken.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends PickupTokenUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, PickupTokenUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$PickupTokenPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one PickupToken.
   * @param {PickupTokenUpsertArgs} args - Arguments to update or create a PickupToken.
   * @example
   * // Update or create a PickupToken
   * const pickupToken = await prisma.pickupToken.upsert({
   *   create: {
   *     // ... data to create a PickupToken
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the PickupToken we want to update
   *   }
   * })
   */
  upsert<T extends PickupTokenUpsertArgs>(args: Prisma.SelectSubset<T, PickupTokenUpsertArgs<ExtArgs>>): Prisma.Prisma__PickupTokenClient<runtime.Types.Result.GetResult<Prisma.$PickupTokenPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of PickupTokens.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PickupTokenCountArgs} args - Arguments to filter PickupTokens to count.
   * @example
   * // Count the number of PickupTokens
   * const count = await prisma.pickupToken.count({
   *   where: {
   *     // ... the filter for the PickupTokens we want to count
   *   }
   * })
  **/
  count<T extends PickupTokenCountArgs>(
    args?: Prisma.Subset<T, PickupTokenCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], PickupTokenCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a PickupToken.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PickupTokenAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends PickupTokenAggregateArgs>(args: Prisma.Subset<T, PickupTokenAggregateArgs>): Prisma.PrismaPromise<GetPickupTokenAggregateType<T>>

  /**
   * Group by PickupToken.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PickupTokenGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends PickupTokenGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: PickupTokenGroupByArgs['orderBy'] }
      : { orderBy?: PickupTokenGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, PickupTokenGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetPickupTokenGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the PickupToken model
 */
readonly fields: PickupTokenFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for PickupToken.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__PickupTokenClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  pickup<T extends Prisma.PickupDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.PickupDefaultArgs<ExtArgs>>): Prisma.Prisma__PickupClient<runtime.Types.Result.GetResult<Prisma.$PickupPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the PickupToken model
 */
export interface PickupTokenFieldRefs {
  readonly id: Prisma.FieldRef<"PickupToken", 'String'>
  readonly pickupId: Prisma.FieldRef<"PickupToken", 'String'>
  readonly toWallet: Prisma.FieldRef<"PickupToken", 'String'>
  readonly amount: Prisma.FieldRef<"PickupToken", 'Int'>
  readonly txHash: Prisma.FieldRef<"PickupToken", 'String'>
  readonly mintedAt: Prisma.FieldRef<"PickupToken", 'DateTime'>
}
    

// Custom InputTypes
/**
 * PickupToken findUnique
 */
export type PickupTokenFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PickupToken
   */
  select?: Prisma.PickupTokenSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PickupToken
   */
  omit?: Prisma.PickupTokenOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PickupTokenInclude<ExtArgs> | null
  /**
   * Filter, which PickupToken to fetch.
   */
  where: Prisma.PickupTokenWhereUniqueInput
}

/**
 * PickupToken findUniqueOrThrow
 */
export type PickupTokenFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PickupToken
   */
  select?: Prisma.PickupTokenSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PickupToken
   */
  omit?: Prisma.PickupTokenOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PickupTokenInclude<ExtArgs> | null
  /**
   * Filter, which PickupToken to fetch.
   */
  where: Prisma.PickupTokenWhereUniqueInput
}

/**
 * PickupToken findFirst
 */
export type PickupTokenFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PickupToken
   */
  select?: Prisma.PickupTokenSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PickupToken
   */
  omit?: Prisma.PickupTokenOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PickupTokenInclude<ExtArgs> | null
  /**
   * Filter, which PickupToken to fetch.
   */
  where?: Prisma.PickupTokenWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of PickupTokens to fetch.
   */
  orderBy?: Prisma.PickupTokenOrderByWithRelationInput | Prisma.PickupTokenOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for PickupTokens.
   */
  cursor?: Prisma.PickupTokenWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` PickupTokens from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` PickupTokens.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of PickupTokens.
   */
  distinct?: Prisma.PickupTokenScalarFieldEnum | Prisma.PickupTokenScalarFieldEnum[]
}

/**
 * PickupToken findFirstOrThrow
 */
export type PickupTokenFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PickupToken
   */
  select?: Prisma.PickupTokenSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PickupToken
   */
  omit?: Prisma.PickupTokenOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PickupTokenInclude<ExtArgs> | null
  /**
   * Filter, which PickupToken to fetch.
   */
  where?: Prisma.PickupTokenWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of PickupTokens to fetch.
   */
  orderBy?: Prisma.PickupTokenOrderByWithRelationInput | Prisma.PickupTokenOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for PickupTokens.
   */
  cursor?: Prisma.PickupTokenWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` PickupTokens from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` PickupTokens.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of PickupTokens.
   */
  distinct?: Prisma.PickupTokenScalarFieldEnum | Prisma.PickupTokenScalarFieldEnum[]
}

/**
 * PickupToken findMany
 */
export type PickupTokenFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PickupToken
   */
  select?: Prisma.PickupTokenSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PickupToken
   */
  omit?: Prisma.PickupTokenOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PickupTokenInclude<ExtArgs> | null
  /**
   * Filter, which PickupTokens to fetch.
   */
  where?: Prisma.PickupTokenWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of PickupTokens to fetch.
   */
  orderBy?: Prisma.PickupTokenOrderByWithRelationInput | Prisma.PickupTokenOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing PickupTokens.
   */
  cursor?: Prisma.PickupTokenWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` PickupTokens from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` PickupTokens.
   */
  skip?: number
  distinct?: Prisma.PickupTokenScalarFieldEnum | Prisma.PickupTokenScalarFieldEnum[]
}

/**
 * PickupToken create
 */
export type PickupTokenCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PickupToken
   */
  select?: Prisma.PickupTokenSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PickupToken
   */
  omit?: Prisma.PickupTokenOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PickupTokenInclude<ExtArgs> | null
  /**
   * The data needed to create a PickupToken.
   */
  data: Prisma.XOR<Prisma.PickupTokenCreateInput, Prisma.PickupTokenUncheckedCreateInput>
}

/**
 * PickupToken createMany
 */
export type PickupTokenCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many PickupTokens.
   */
  data: Prisma.PickupTokenCreateManyInput | Prisma.PickupTokenCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * PickupToken createManyAndReturn
 */
export type PickupTokenCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PickupToken
   */
  select?: Prisma.PickupTokenSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the PickupToken
   */
  omit?: Prisma.PickupTokenOmit<ExtArgs> | null
  /**
   * The data used to create many PickupTokens.
   */
  data: Prisma.PickupTokenCreateManyInput | Prisma.PickupTokenCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PickupTokenIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * PickupToken update
 */
export type PickupTokenUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PickupToken
   */
  select?: Prisma.PickupTokenSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PickupToken
   */
  omit?: Prisma.PickupTokenOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PickupTokenInclude<ExtArgs> | null
  /**
   * The data needed to update a PickupToken.
   */
  data: Prisma.XOR<Prisma.PickupTokenUpdateInput, Prisma.PickupTokenUncheckedUpdateInput>
  /**
   * Choose, which PickupToken to update.
   */
  where: Prisma.PickupTokenWhereUniqueInput
}

/**
 * PickupToken updateMany
 */
export type PickupTokenUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update PickupTokens.
   */
  data: Prisma.XOR<Prisma.PickupTokenUpdateManyMutationInput, Prisma.PickupTokenUncheckedUpdateManyInput>
  /**
   * Filter which PickupTokens to update
   */
  where?: Prisma.PickupTokenWhereInput
  /**
   * Limit how many PickupTokens to update.
   */
  limit?: number
}

/**
 * PickupToken updateManyAndReturn
 */
export type PickupTokenUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PickupToken
   */
  select?: Prisma.PickupTokenSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the PickupToken
   */
  omit?: Prisma.PickupTokenOmit<ExtArgs> | null
  /**
   * The data used to update PickupTokens.
   */
  data: Prisma.XOR<Prisma.PickupTokenUpdateManyMutationInput, Prisma.PickupTokenUncheckedUpdateManyInput>
  /**
   * Filter which PickupTokens to update
   */
  where?: Prisma.PickupTokenWhereInput
  /**
   * Limit how many PickupTokens to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PickupTokenIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * PickupToken upsert
 */
export type PickupTokenUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PickupToken
   */
  select?: Prisma.PickupTokenSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PickupToken
   */
  omit?: Prisma.PickupTokenOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PickupTokenInclude<ExtArgs> | null
  /**
   * The filter to search for the PickupToken to update in case it exists.
   */
  where: Prisma.PickupTokenWhereUniqueInput
  /**
   * In case the PickupToken found by the `where` argument doesn't exist, create a new PickupToken with this data.
   */
  create: Prisma.XOR<Prisma.PickupTokenCreateInput, Prisma.PickupTokenUncheckedCreateInput>
  /**
   * In case the PickupToken was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.PickupTokenUpdateInput, Prisma.PickupTokenUncheckedUpdateInput>
}

/**
 * PickupToken delete
 */
export type PickupTokenDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PickupToken
   */
  select?: Prisma.PickupTokenSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PickupToken
   */
  omit?: Prisma.PickupTokenOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PickupTokenInclude<ExtArgs> | null
  /**
   * Filter which PickupToken to delete.
   */
  where: Prisma.PickupTokenWhereUniqueInput
}

/**
 * PickupToken deleteMany
 */
export type PickupTokenDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which PickupTokens to delete
   */
  where?: Prisma.PickupTokenWhereInput
  /**
   * Limit how many PickupTokens to delete.
   */
  limit?: number
}

/**
 * PickupToken without action
 */
export type PickupTokenDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PickupToken
   */
  select?: Prisma.PickupTokenSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PickupToken
   */
  omit?: Prisma.PickupTokenOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PickupTokenInclude<ExtArgs> | null
}
