
// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";

// Only use this if you have a custom Prisma config
// Otherwise, Prisma will use the default schema.prisma location
export const prismaConfig = {
  schema: "prisma/schema.prisma",
};
